name: quantum-networking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pandas
  - pip:
    - -r binder_requirements.txt
