name: quantum-networking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - ipywidgets
  - nodejs
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - pydantic-settings
      - python-multipart
      - httpx
      - websockets
      - jinja2
      - aiofiles
      - requests
      - tqdm
      - typing-extensions
      - click
      - rich
      - colorama
      - python-dotenv
      - pyyaml
      - toml
      - psutil
      - redis
      - cryptography
      - pycryptodome
      - openai
      - markdown
      - openpyxl
      - xlsxwriter
      - pytest
      - pytest-asyncio