name: quantum-networking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - nodejs=18
  - npm=9
  - numpy=1.26
  - scipy=1.16
  - pandas=2.0
  - matplotlib-base=3.8
  - networkx
  - qutip=5.0.4
  - ipywidgets=8
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - pydantic-settings
      - python-multipart
      - httpx
      - websockets
      - jinja2
      - aiofiles
      - requests
      - tqdm
      - typing-extensions
      - click
      - rich
      - colorama
      - python-dotenv
      - pyyaml
      - toml
      - psutil
      - redis
      - redis-om
      - cryptography
      - pycryptodome
      - openai
      - langchain
      - langchain-openai
      - markdown
      - openpyxl
      - xlsxwriter
      - pytest
      - pytest-asyncio
