name: quantum-networking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # heavy scientific bits via conda (faster & stable)
  - numpy=1.26.*
  - scipy=1.16.*
  - pandas>=2,<3
  - matplotlib-base>=3.8,<3.11  # headless, avoids Qt/PySide
  - networkx
  - qutip=5.*
  - ipywidgets>=8
    - pip:
      # core web framework
      - fastapi
      - uvicorn[standard]
      - pydantic
      - pydantic-settings
      - python-multipart
      - httpx
      - websockets
      - jinja2
      - aiofiles
      - requests

      # essential utilities
      - tqdm
      - typing-extensions
      - click
      - rich
      - colorama
      - python-dotenv
      - pyyaml
      - toml
      - psutil

      # quantum networking essentials
      - redis
      - redis-om
      - cryptography
      - pycryptodome

      # AI/ML (minimal set)
      - openai
      - langchain
      - langchain-openai
      - markdown

      # data handling
      - openpyxl
      - xlsxwriter

      # testing
      - pytest
      - pytest-asyncio