name: quantum-networking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nodejs=18
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - numpy
    - matplotlib
    - jupyter
    - ipywidgets
    - requests
