name: quantum-networking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - networkx
  - pandas
  - pip:
    - fastapi>=0.104.0,<0.109.0
    - uvicorn[standard]>=0.24.0,<0.30.0
    - pydantic>=2.0.0,<3.0.0
    - pydantic-settings>=2.0.0,<3.0.0
    - python-multipart>=0.0.6
    - qutip==5.0.4
    - httpx>=0.25.0,<0.28.0
    - websockets>=12.0,<13.0
    - jinja2>=3.1.0,<4.0.0
    - aiofiles>=23.0.0,<24.0.0
    - requests>=2.28.0,<3.0.0
    - jupyter>=1.0.0,<2.0.0
    - ipywidgets>=8.0.0,<9.0.0
    - ipykernel>=6.25.0,<7.0.0
    - jupyter-contrib-nbextensions>=0.7.0,<1.0.0
    - notebook>=7.0.0,<8.0.0
    - pandas>=1.5.0,<3.0.0
    - tqdm>=4.62.0,<5.0.0
    - typing-extensions>=4.0.0,<5.0.0
    - click>=8.0.0,<9.0.0
    - rich>=13.0.0,<14.0.0
    - colorama>=0.4.0,<1.0.0
    - python-dotenv>=1.0.0,<2.0.0
    - seaborn>=0.11.0,<1.0.0
    - plotly>=5.0.0,<6.0.0
    - openai>=1.0.0,<2.0.0
    - langchain-openai>=0.1.0,<1.0.0
    - langchain>=0.1.0,<1.0.0
    - markdown>=3.5.0,<4.0.0
    - cryptography>=3.4.0,<42.0.0
    - pycryptodome>=3.15.0,<4.0.0
    - aiohttp>=3.8.0,<4.0.0
    - websocket-client>=1.3.0,<2.0.0
    - openpyxl>=3.0.0,<4.0.0
    - xlsxwriter>=3.0.0,<4.0.0
    - pyyaml>=6.0,<7.0.0
    - toml>=0.10.0,<1.0.0
    - psutil>=5.9.0,<6.0.0
    - pytest>=7.4.0,<8.0.0
    - pytest-asyncio>=0.21.0,<1.0.0
    - redis>=5.0.0,<6.0.0
    - redis-om>=0.1.0,<1.0.0
