name: quantum-networking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # heavy scientific bits via conda (faster & stable)
  - numpy=1.26.*
  - scipy=1.16.*
  - pandas>=2,<3
  - matplotlib-base>=3.8,<3.11  # headless, avoids Qt/PySide
  - networkx
  - qutip=5.*
  - ipywidgets>=8
  - pip:
      # backend + web stack
      - fastapi>=0.104,<0.109
      - uvicorn[standard]>=0.24,<0.30
      - pydantic>=2,<3
      - pydantic-settings>=2,<3
      - python-multipart>=0.0.6
      - httpx>=0.25,<0.28
      - websockets>=12,<13
      - jinja2>=3.1,<4
      - aiofiles>=23,<24
      - requests>=2.28,<3

      # notebook/runtime helpers (Binder already has Jupyter)
      - ipykernel>=6.26,<7
      - tqdm>=4.62,<5
      - typing-extensions>=4,<5
      - click>=8,<9
      - rich>=13,<14
      - colorama>=0.4,<1

      # your extras
      - python-dotenv>=1,<2
      - seaborn>=0.13,<0.14
      - plotly>=5,<6
      - openai>=1,<2
      - langchain-openai>=0.1,<1
      - langchain>=0.1,<1
      - markdown>=3.5,<4
      - cryptography>=41,<43
      - pycryptodome>=3.15,<4
      - aiohttp>=3.8,<3.9
      - websocket-client>=1.3,<2
      - openpyxl>=3,<4
      - xlsxwriter>=3,<4
      - pyyaml>=6,<7
      - toml>=0.10,<1
      - psutil>=5.9,<6
      - pytest>=7.4,<8
      - pytest-asyncio>=0.21,<0.22
      - redis>=5,<6
      - redis-om>=0.1,<0.2